title: Amanda Lubin
logo: /assets/img/headshot_circle.png([!image](https://i.pinimg.com/564x/9d/55/52/9d5552f6bc892569f22d8b6b7b1bb559.jpg))
#description: text below image
show_downloads: false
theme: jekyll-theme-minimal
