title: Amanda Lubin
logo: /assets/img/headshot_circle.png(!https://i.pinimg.com/736x/a2/bb/d7/a2bbd7c39245cd5c5e5aea12f911d34f.jpg)

#description: text below image
show_downloads: false
theme: jekyll-theme-minimal
